# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master
pool:
  vmImage: 'vs2017-win2016'
variables:
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/master')]
stages:
- stage: NPMInstall
  displayName: NPM Install
  jobs:
    - job: NpmInstall
      steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '10.x'
        displayName: 'Install Node.js'
      - script: |
          npm config set @sap:registry "https://npm.sap.com"
          npm install
        displayName: 'npm install'
- stage: PluginInstall
  displayName: Install Plugin
  dependsOn: NPMInstall
  condition: and(succeeded(), eq(variables.isMain, true))
  jobs:
    - job: InstallPlugin
      displayName: Install Plugin
      steps:
      - script: |
          npm install --save-dev eslint
        displayName: 'Install eslint'
      - script: |
          npm install karma --save-dev
        displayName: 'Install Karma'
      - script: |
          npm install karma-cli
        displayName: 'Install karma-Cli'
      - script: |
          npm i -g rimraf
        displayName: 'Install rimraf'
      - script: |
          npm install --global @ui5/cli
        displayName: 'UI5-cli'
      - script: |
          npm install -g grunt-nwabap-ui5uploader
        displayName: Install grunt ui5 uploader
- stage: ReviewTest
  displayName: Review and Test
  dependsOn: PluginInstall
  condition: and(succeeded(), eq(variables.isMain, true))
  jobs:
    - job: RunReview
      displayName: Code Review
      steps:
      - script: |
          npm run lint
        displayName: 'Run eslint'
    - job: RunTest
      displayName: UI5 test
      dependsOn: RunReview
      steps:
      - script: |
          npm run karma-ci
        displayName: 'Run unit test and opa test'
- stage: BuildDeploy
  displayName: Build and Deploy
  dependsOn: ReviewTest
  condition: and(succeeded(), eq(variables.isMain, true))
  jobs:
    - job: buildcode
      displayName: Build UI5
      steps:
      - script: |
          ui5 build -a --clean-dest
        displayName: 'Build Application'
    - job: deploycode
      displayName: Deploy Code
      dependsOn: buildcode
      steps:
      - script: |
          grunt --username="DEV_ECQ2" --password="Welcome1" --server="http://in-blr-1709:8000" --request="S48K901584" --pkg="ZAZUREDEVOPS"
        displayName: 'Deploy process'

