# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master
pool:
  vmImage: 'ubuntu-latest' 

stages:
- stage: NPMInstall
  displayName: NPM Install
  jobs:
    - job: NpmInstall
      steps:
        - task: NodeTool@0
          inputs:
            versionSpec: '10.x'
          displayName: 'Install Node.js'
        - script: |
              npm config set @sap:registry "https://npm.sap.com"
              npm install
          displayName: 'npm install'
- stage: InstallPlugin
  displayName: Install Plugin
  dependsOn: NPMInstall
  jobs:
    - job: InstallPlugin
      steps:
        - script: |
            'npm install --save-dev eslint'
          displayName: 'Install eslint'
        - script: |
            'npm install karma --save-dev'
          displayName: 'Install Karma' 
        - script: |
            'npm install karma-cli'
          displayName: 'Install karma-Cli'
        - script: |
            'npm install --global rimraf'
          displayName: 'Install rimraf'
        - script: |
            'npm install --global @ui5/cli'
          displayName: 'Install UI5-cli'        
        - script: |
            'npm install -g grunt grunt-cli grunt-nwabap-ui5uploader'
          displayName: 'Install grunt grunt-cli'
- stage: Testing
  displayName: Review and test
  dependsOn: InstallPlugin
  jobs:
    - job: Review
      steps:
        - script: |
            npm run lint
          displayName: 'Run eslint'
    - job: UI5test
      steps:
        - script: |
            npm run karma-ci
          displayName: 'Run unit test and opa test'
- stage: Build
  displayName: Build And Deploy
  dependsOn: Testing
  jobs:
    - job: Build
      steps:    
        - script: |
            ui5 build -a --clean-dest
          displayName: 'Build Application'
    - job: Deploy
      steps:
        - script: |
            grunt --username="DEV_ECQ2" --password="Welcome1" --server="http://in-blr-1709:8000" --request="S48K901584" --pkg="ZAZUREDEVOPS"
          displayName: 'Deploy process'

