# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master
pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'
- task: CmdLine@2
  inputs:
    script: |
      echo Write your commands here
      
      echo Hello world
- script: |
    npm config set @sap:registry "https://npm.sap.com"
    npm install
  displayName: 'npm install'
- script: |
    npm install --save-dev eslint
  displayName: 'Install eslint'
- script: |
    npm run lint
  displayName: 'Run eslint'
- script: |
    npm install karma --save-dev
  displayName: 'Install Karma'
- script: |
    npm install karma-cli
  displayName: 'Install karma-Cli'
- script: |
    npm i -g rimraf
  displayName: 'Install rimraf'
- script: |
    npm run karma-ci
  displayName: 'Run unit test and opa test'
- script: |
    npm install --global @ui5/cli
  displayName: 'UI5-cli'
- script: |
    ui5 build -a --clean-dest
  displayName: 'Build Application'
- script: |
    npm install -g grunt grunt-cli grunt-nwabap-ui5uploader
  displayName: Install grunt grunt-cli
- script: |
    grunt --username="DEV_ECQ2" --password="Welcome1" --server="http://in-blr-1709:8000" --request="S48K901584" --pkg="ZAZUREDEVOPS"
  displayName: 'Deploy process'

